### ISSUE TITLE
Investigate where readlink() is coming from when Python is launched on cori.

### ISSUE THREAD

**Issue by mcfadden8** [hpc/Spindle#17]

**Comment by mplegendre** [comment]
@mcfadden8 and I discovered the readlinks of /proc/self/exe are coming from the dynamic linker when the binary contains an $ORIGIN rpath.  We're failing to intercept and correct these because they're a direct syscall rather than through libc's readlink.  The result of this is that $ORIGIN is expanded to Spindle's cache location where we stashed the executable, and the applications library search path is wrong.

Am closing this "to investigate" issue.  It's fixed by running Spindle with "--debug=yes", and we'll use issue #16 to look into making "--debug=yes" default behavior.
